[api]
    dashboard = true
    debug = true
    insecure = true
[providers.docker]
    exposedByDefault = true
    swarmMode = true
    network = "proxynetwork"
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    defaultRule = "HostRegexp(`{{ index .Labels \"com.docker.compose.service\"}}.traefik.me`,`{{ index .Labels \"com.docker.compose.service\"}}-{dashed-ip:.*}.traefik.me`)"
[entryPoints]
    [entryPoints.web]
        address = ":80"
    [entryPoints.web-secure]
        address = ":443"